### ISSUE TITLE
Zombies: poison bite

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#386]

**Comment by red-kangaroo** [comment]
This would be great, because right now zombies are very weak as minions and giving them a natural poison attack would balance them nicely.

**Comment by Hunteil** [comment]
Could be a upgrade ability thing too.

I do recall playing through a game as adventure mode, where the Keeper had a few zombies. I kept chopping off limbs but they wouldn't die until I got them just right. Their limbs started to rot and poisonous gas came out. Over time I killed I think 3 zombies, a few Orcs. But the poison over time killed me and I wasn't able to progress into base b/c they just wouldn't die. (this was a older version)

Recently did a stint through some catacombs with zombies, same thing happened, except my weapon was better and I killed them way faster this time. idk if there was a change or just luck. I think it might be more the fact that I had better equipment due to the current design on the game allowing you to travel.

**Comment by red-kangaroo** [comment]
BTW, this could be a nice alternative to poison bite. Let zombies "decay" naturally, trailing poison gas behind them. This would make them a walking gas trap and quite interesting to use in combat, IMHO.

They should avoid poisoning your other minions (probably hanging out in graveyard more than with others), though.

**Comment by Hunteil** [comment]
> BTW, this could be a nice alternative to poison bite. Let zombies "decay" naturally, trailing poison gas behind them. This would make them a walking gas trap and quite interesting to use in combat, IMHO.

> They should avoid poisoning your other minions (probably hanging out in graveyard more than with others), though.

I foresee that being as bad as the pigs poisoning our minions now.

**Comment by GameDoungen** [comment]
Added
